package com.example.factsapp;

public class Facts {

    public static String[] getFacts(){

        return new String[]{

                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
                "Dolphins are unable to smell.",
                "When grazing or resting, cows tend to align their bodies with the magnetic north and south poles.",
                "The King of Hearts is the only king without a mustache.",
                "The Hawaiian alphabet has only 12 letters.",
                "Lizards communicate by doing push-ups.",
                "A spider’s silk is stronger than steel",
                "Every ton of recycled paper saves about 17 trees.",
                "There are more tigers owned by Americans than in the wild worldwide.",
                "Sailors once thought wearing gold earrings improved eyesight.",
                "Mexican jumping beans jump to get out of sunlight.",
        };
    }
}